import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({weight: ['300', '400', '900'], subsets: ['latin']})

export const metadata = {
  title: {
       default: 'Data-Fetch',
       template: '%s | Data-Fetch'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Nav></Nav>
        {children}
      </body>
    </html>
  );
}
